### ISSUE TITLE
bdp error when result involves arrays

### ISSUE THREAD

**Issue by sob727** [alpha-xone/xbbg#21]
Hi,

I'm trying to use bdp to retrieve fields that typically return arrays (on the Terminal, under FLDS, such fields can be identified by the "Show Bulk Data" mention in the "Value" column.

Windows 10
Python 3.8.6
blpapi 3.15.2
xbbg 0.7.0

```
blp.bdp('TYA Index','FUT_CHAIN')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\S\PycharmProjects\test_bbg\venv\lib\site-packages\xbbg\blp.py", line 46, in bdp
    res
  File "C:\Users\S\PycharmProjects\test_bbg\venv\lib\site-packages\pandas\core\frame.py", line 7142, in unstack
    return unstack(self, level, fill_value)
  File "C:\Users\S\PycharmProjects\test_bbg\venv\lib\site-packages\pandas\core\reshape\reshape.py", line 418, in unstack
    return _unstack_frame(obj, level, fill_value=fill_value)
  File "C:\Users\S\PycharmProjects\test_bbg\venv\lib\site-packages\pandas\core\reshape\reshape.py", line 438, in _unstack_frame
    return _Unstacker(
  File "C:\Users\S\PycharmProjects\test_bbg\venv\lib\site-packages\pandas\core\reshape\reshape.py", line 120, in __init__
    self._make_selectors()
  File "C:\Users\S\PycharmProjects\test_bbg\venv\lib\site-packages\pandas\core\reshape\reshape.py", line 169, in _make_selectors
    raise ValueError("Index contains duplicate entries, cannot reshape")
```

The returned value doesn't sit well with the unstack function from pandas. Let me know if there's more info I can provide.

**Comment by alpha-xone** [comment]
Need to use `blp.bds` for bulk data

**Comment by sob727** [comment]
I stand corrected. Thank you Sir.

**Comment by kamilla2101** [comment]
have the same issue,  exactly the same list of securities works for one source (fixed income) test = blp.bdp(isin,"PX_BID"), but doesn't work for another source. It shows:    
`189 mask.put(selector, True)
    191 if mask.sum() < len(self.index):
--> 192     raise ValueError("Index contains duplicate entries, cannot reshape")
    194 self.group_index = comp_index
    195 self.mask = mask

ValueError: Index contains duplicate entries, cannot reshape`
